FIRE_START_PROB_DEVEL = .01
FIRE_CATCH_PROB_DEVEL = .3
FIRE_START_PROB_WILD = 0.0005
FIRE_CATCH_PROB_WILD = .4
MAX_EST_FIRE_PROB = .04

TIME_HORIZON = 50 #years
DENSITY_OF_HOMES = .01
MEAN_COST_TO_DEVELOP = 1
STD_COST_TO_DEVELOP = MEAN_COST_TO_DEVELOP / float(5)
MEAN_RENT = MEAN_COST_TO_DEVELOP / float(TIME_HORIZON+20)
STD_RENT = MEAN_RENT / float(10)

BURNT_REGEN_TIME = 1
NEIGHBOR_WINDOW = 1

